name: service_forecast

services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
#    ports:
#      - "5432:5432"
    volumes:
      - toir_app_data:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c timezone=UTC
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks: [internal]

  migrations:
    build:
      context: ../src/toir_app/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["alembic", "upgrade", "head"]
    networks: [internal]

  backend:
    build:
      context: ../src/toir_app/
      pull: false  # тест локального образа
    image: python:3.11-slim  # тест локального образа
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8877:8877"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks: [internal]

  frontend:
    build: ../src/Frontend/
    command: cp -r /app/dist/spa/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  # frontend:
  #   build:
  #     context: ../src/Frontend/
  #   #   pull: false  # Тест локального образа
  #   # image: node:20-alpine  # Тест локального образа
  #   volumes:
  #     - ../src/Frontend:/app          # Монтируем исходный код
  #     - static_volume:/app/static      # Для статики
  #     - /app/node_modules              # Защита node_modules
  #   #command: >
  #   #  sh -c "npm install &&
  #   #         npm run build &&
  #   #         cp -R dist/* /app/static/ &&
  #   #         exit 0"  # Явное завершение
  #   env_file:
  #     - .env
  #   depends_on:
  #     backend:
  #       condition: service_started
  #   networks: [internal]

  gateway:
    build: ./nginx/
    ports:
      - 8811:80
    depends_on:
      - backend
    networks: [internal]
    volumes:
      - static:/staticfiles/

volumes:
  toir_app_data:
  migrations:
  static:

networks:
  internal:
    driver: bridge
