server {
  listen 8811;

  index index.html;

  # charset utf-8;

  location /docs/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:8877/docs/;
  }

  location / {
    alias /static/;
    try_files $uri $uri/ /index.html;
  }

}
