"""add zvr_create_date in ServiceWork

Revision ID: 4180419d0eee
Revises: 12a9f5e8718c
Create Date: 2025-05-24 21:34:23.745835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4180419d0eee'
down_revision: Union[str, None] = '12a9f5e8718c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'servicework',
        sa.Column(
            'zvr_create_date',
            sa.DateTime(),
            nullable=True,
            comment='Дата создания ЗВР'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicework', 'zvr_create_date')
    # ### end Alembic commands ###
