"""add group in service_name

Revision ID: 349e0ab8d9d2
Revises: 6982a578f9ea
Create Date: 2025-06-12 17:33:34.635640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349e0ab8d9d2'
down_revision: Union[str, None] = '6982a578f9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicename', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicename', schema=None) as batch_op:
        batch_op.drop_column('group')

    # ### end Alembic commands ###
