"""first_migration

Revision ID: 12be319c3b0c
Revises: 
Create Date: 2025-05-11 10:02:36.285174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12be319c3b0c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carmodel',
    sa.Column('name', sa.String(length=50), nullable=False, comment='Бренд + модификация Автомобиля'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization',
    sa.Column('name', sa.String(length=3), nullable=False, comment='Название подразделения в формате Ю51'),
    sa.Column('normal_name', sa.String(length=5), nullable=True, comment='Название цеха в привычном формате.'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('servicename',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servicestatus',
    sa.Column('name', sa.String(length=20), nullable=False, comment='Рассчётный статус для каждой записи из OeBS'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('specialstatus',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('car',
    sa.Column('personal_id', sa.Integer(), nullable=False, comment='Уникальный ID из OeBS'),
    sa.Column('grz', sa.String(length=20), nullable=False, comment='Государственный регистрационный знак'),
    sa.Column('in_archive', sa.Boolean(), nullable=True, comment='Флаг нахождения в архиве (при списании/продаже)'),
    sa.Column('car_model_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('special_status_id', sa.Integer(), nullable=True, comment='Глобальные статусы (на ВР, к выбытию, на реализации и т.д.)'),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_model_id'], ['carmodel.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['special_status_id'], ['specialstatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grz'),
    sa.UniqueConstraint('personal_id')
    )
    op.create_table('servicework',
    sa.Column('last_service_date', sa.DateTime(), nullable=False, comment='Дата последнего обслуживания'),
    sa.Column('last_service_reading', sa.Float(), nullable=False, comment='Пробег при последнем обслуживании'),
    sa.Column('request_date', sa.DateTime(), nullable=False, comment='Дата запроса (получение файла csv)'),
    sa.Column('request_reading', sa.Float(), nullable=False, comment='Показания на дату запроса (получение файла csv)'),
    sa.Column('base_interval', sa.Float(), nullable=False, comment='Базовый интервал обслуживания (получение csv)'),
    sa.Column('daily_distance', sa.Float(), nullable=False, comment='Среднесуточный пробег (получение csv)'),
    sa.Column('zrv_number', sa.String(length=14), nullable=True, comment='ЗВР для данной работы'),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('last_service_id', sa.Integer(), nullable=True),
    sa.Column('next_service_id', sa.Integer(), nullable=True),
    sa.Column('request_status_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
    sa.ForeignKeyConstraint(['last_service_id'], ['servicename.id'], ),
    sa.ForeignKeyConstraint(['next_service_id'], ['servicename.id'], ),
    sa.ForeignKeyConstraint(['request_status_id'], ['servicestatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zrv_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicework')
    op.drop_table('car')
    op.drop_table('specialstatus')
    op.drop_table('servicestatus')
    op.drop_table('servicename')
    op.drop_table('role')
    op.drop_table('organization')
    op.drop_table('carmodel')
    # ### end Alembic commands ###
