"""join special_status and car and user

Revision ID: addc112da2f1
Revises: 3dc4cbd4a09c
Create Date: 2025-06-25 23:08:31.562277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'addc112da2f1'
down_revision: Union[str, None] = '3dc4cbd4a09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'specialstatusforcar',
        sa.Column('date_left', sa.Date(), nullable=False),
        sa.Column('comment', sa.String(length=200), nullable=True),
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=True,
            comment='Актуальность статуса для ТС'
        ),
        sa.Column('car_id', sa.Integer(), nullable=False),
        sa.Column('special_status_id', sa.Integer(), nullable=False),
        sa.Column('assigned_by_user_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['assigned_by_user_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['car_id'], ['car.id'], ),
        sa.ForeignKeyConstraint(['special_status_id'], ['specialstatus.id'], ),
        sa.PrimaryKeyConstraint('car_id', 'special_status_id', 'id'),
        sa.UniqueConstraint(
            'car_id',
            'special_status_id',
            name='uq_special_status_for_car'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialstatusforcar')
    # ### end Alembic commands ###
