"""add in_archive in ServiceWork model

Revision ID: 12a9f5e8718c
Revises: 12be319c3b0c
Create Date: 2025-05-24 16:13:26.201197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a9f5e8718c'
down_revision: Union[str, None] = '12be319c3b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'servicework',
        sa.Column(
            'in_archive',
            sa.Boolean(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicework', 'in_archive')
    # ### end Alembic commands ###
