"""upd zvr value

Revision ID: 08793dfb2386
Revises: addc112da2f1
Create Date: 2025-07-24 10:24:40.315074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08793dfb2386'
down_revision: Union[str, None] = 'addc112da2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.alter_column(
            'zrv_number',
            existing_type=sa.VARCHAR(length=14),
            type_=sa.String(length=15),
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.alter_column(
            'zrv_number',
            existing_type=sa.String(length=15),
            type_=sa.VARCHAR(length=14),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
