"""add service_work_completed in ServiceWork 

Revision ID: 3f67d2a61f99
Revises: 4180419d0eee
Create Date: 2025-05-24 22:59:18.003037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f67d2a61f99'
down_revision: Union[str, None] = '4180419d0eee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'servicework',
        sa.Column(
            'service_work_completed',
            sa.Boolean(),
            nullable=True,
            comment='Работы завершены, но ЗВР пока не закрыт'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicework', 'service_work_completed')
    # ### end Alembic commands ###
