"""add2 stats for organization

Revision ID: 2c0ca2b61325
Revises: 1ff5955b216f
Create Date: 2025-06-22 22:07:08.004606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0ca2b61325'
down_revision: Union[str, None] = '1ff5955b216f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'servicestatusstats',
        sa.Column(
            'stats_date',
            sa.DateTime(),
            nullable=False,
            comment='Дата сбора данных (после обработки файла csv)'
        ),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('danger_slice_id', sa.Integer(), nullable=False),
        sa.Column('time_has_come_slice_id', sa.Integer(), nullable=False),
        sa.Column('wait_moment_slice_id', sa.Integer(), nullable=False),
        sa.Column('no_need_slice_id', sa.Integer(), nullable=False),
        sa.Column('bad_reqiest_slice_id', sa.Integer(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organization.id'],
        ),
        sa.ForeignKeyConstraint(
            ['danger_slice_id'], ['serviceworkstate.id'],
        ),
        sa.ForeignKeyConstraint(
            ['time_has_come_slice_id'], ['serviceworkstate.id'],
        ),
        sa.ForeignKeyConstraint(
            ['wait_moment_slice_id'], ['serviceworkstate.id'],
        ),
        sa.ForeignKeyConstraint(
            ['no_need_slice_id'], ['serviceworkstate.id'],
        ),
        sa.ForeignKeyConstraint(
            ['bad_reqiest_slice_id'], ['serviceworkstate.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('bad_reqiest_slice_id'),
        sa.UniqueConstraint('danger_slice_id'),
        sa.UniqueConstraint('no_need_slice_id'),
        sa.UniqueConstraint('time_has_come_slice_id'),
        sa.UniqueConstraint('wait_moment_slice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicestatusstats')
    # ### end Alembic commands ###
