"""изменил длину имени service_status_name_len

Revision ID: 474ec254a05b
Revises: 9a3961b78389
Create Date: 2025-04-28 11:29:05.677005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474ec254a05b'
down_revision: Union[str, None] = '9a3961b78389'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == 'sqlite':
        with op.batch_alter_table('servicename') as batch_op:
            batch_op.alter_column('name', type_=sa.String(length=40))
    else:
        op.alter_column('servicename', 'name',
                        existing_type=sa.VARCHAR(length=20),
                        type_=sa.String(length=40),
                        existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_context().dialect.name == 'sqlite':
        with op.batch_alter_table('servicename') as batch_op:
            batch_op.alter_column('name', type_=sa.String(length=20))
    else:
        op.alter_column('servicename', 'name',
                        existing_type=sa.String(length=40),
                        type_=sa.VARCHAR(length=20),
                        existing_nullable=False)
    # ### end Alembic commands ###
