"""add stats for service_work

Revision ID: 1ff5955b216f
Revises: 8b7355c574ac
Create Date: 2025-06-22 19:06:12.459482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff5955b216f'
down_revision: Union[str, None] = '8b7355c574ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'serviceworkstate',
        sa.Column(
            'with_open_zvr',
            sa.Integer(),
            nullable=False,
            comment='В состоянии с открытым ЗВР'
        ),
        sa.Column(
            'de_facto_completed',
            sa.Integer(),
            nullable=False,
            comment='В состоянии фактического завершения'
        ),
        sa.Column(
            'without_zvr',
            sa.Integer(),
            nullable=False,
            comment='В состоянии без ЗВР'
        ),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serviceworkstate')
    # ### end Alembic commands ###
