"""Add tg_uuid to car

Revision ID: 5045769ec1f3
Revises: 4478ac2de337
Create Date: 2025-10-03 20:43:43.966569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5045769ec1f3'
down_revision: Union[str, None] = '4478ac2de337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'tg_uuid',
            sa.String(length=32),
            nullable=True,
            comment='Уникальный UUID ТС',
        ))
        batch_op.create_unique_constraint('uq_car_tg_uuid', ['tg_uuid'])


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_constraint('uq_car_tg_uuid', type_='unique')
        batch_op.drop_column('tg_uuid')
