"""add user

Revision ID: 6982a578f9ea
Revises: 3f67d2a61f99
Create Date: 2025-06-07 18:27:43.705839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6982a578f9ea'
down_revision: Union[str, None] = '3f67d2a61f99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.PrimaryKeyConstraint('id'),
        sa.Column(
            'name',
            sa.String(length=40),
            nullable=False,
            comment='Имя пользователя'
        ),
        sa.Column(
            'surname',
            sa.String(length=40),
            nullable=False,
            comment='Фамилия пользователя'
        ),
        sa.Column(
            'organization_id',
            sa.Integer(),
            nullable=False,
            comment='Связь с подразделением через его ID.'
        ),
        sa.Column(
            'role_id',
            sa.Integer(),
            nullable=False,
            comment='Связь с полномочиями через их ID.'
        ),
        sa.Column('email', sa.String(length=320), nullable=False),
        sa.Column('hashed_password', sa.String(length=1024), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_superuser', sa.Boolean(), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
