"""new value for service_work_completed

Revision ID: 946c2bb5e61a
Revises: 08793dfb2386
Create Date: 2025-07-24 15:02:34.029806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946c2bb5e61a'
down_revision: Union[str, None] = '08793dfb2386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.alter_column(
            'service_work_completed',
            existing_type=sa.BOOLEAN(),
            type_=sa.DateTime(),
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.alter_column(
            'service_work_completed',
            existing_type=sa.DateTime(),
            type_=sa.BOOLEAN(),
            existing_nullable=True
        )

    # ### end Alembic commands ###
