"""add_role_in_special_status

Revision ID: 9dcf22735877
Revises: 946c2bb5e61a
Create Date: 2025-08-06 11:33:42.053452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9dcf22735877'
down_revision: Union[str, None] = '946c2bb5e61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'special_status_role_association',
        sa.Column('special_status_id', sa.Integer(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.ForeignKeyConstraint(['special_status_id'], ['specialstatus.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('special_status_role_association')
    # ### end Alembic commands ###
