"""add station

Revision ID: 8b7355c574ac
Revises: 349e0ab8d9d2
Create Date: 2025-06-20 12:29:48.454324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7355c574ac'
down_revision: Union[str, None] = '349e0ab8d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'station',
        sa.Column(
            'name',
            sa.String(length=10),
            nullable=False,
            comment='Название зоны сервиса'
        ),
        sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('station_id', sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            'fk_service_work_station_id_station',
            'station',
            ['station_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicework', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_service_work_station_id_station', type_='foreignkey'
        )
        batch_op.drop_column('station_id')

    op.drop_table('station')
    # ### end Alembic commands ###
